# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/garahe_db
spring.datasource.username=root
spring.datasource.password=Phen02082004*

# Auto-create tables (The Magic Setting)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true